management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: angadi
    description: authentic telugu e commerce store.
    author: kishore j
    version: '@project.version@'
spring:
  profiles:
    active: dev